# Generated by Django 5.1.5 on 2025-01-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incomes", "0003_alter_income_account_alter_income_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="create_at",
            field=models.DateTimeField(verbose_name="Дата операции"),
        ),
    ]
