# Generated by Django 5.1.5 on 2025-03-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incomes", "0006_alter_income_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="income",
            options={
                "ordering": ["-create_at", "category__name"],
                "verbose_name": "доход",
                "verbose_name_plural": "доходы",
            },
        ),
    ]
