# Generated by Django 5.1.5 on 2025-03-03 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transfer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrower_description", models.CharField(max_length=100)),
                (
                    "transfer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debt",
                        to="transfer.transfer",
                    ),
                ),
            ],
            options={
                "verbose_name": "долг",
                "verbose_name_plural": "долги",
                "ordering": ["-transfer__timestamp"],
            },
        ),
    ]
