services:
  finance_db:
    image: postgres:15-alpine
    container_name: finance-db
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASS}"
      - "POSTGRES_DB=${DB_NAME}"
    ports:
      - '127.0.0.1:5432:5432'
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  django_app:
    build:
      context: ./finance
    container_name: api
    restart: unless-stopped
    expose:
      - "8001"
    env_file:
      - .env
    depends_on:
      finance_db:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./finance:/finance
    entrypoint: /finance/entrypoint.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  vue_app:
    build:
      context: ./finance-app
    container_name: vue-app
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      django_app:
        condition: service_started
    networks:
      - app_network

  swag:
    image: lscr.io/linuxserver/swag:latest      # Официальный образ
    container_name: swag                        # Имя контейнера
    cap_add:
      - NET_ADMIN                               # Права для работы fail2ban [citation:4]
    environment:
      - PUID=1000                               # ID вашего пользователя
      - PGID=1000                               # ID вашей группы
      - TZ=Europe/Moscow                        # Ваш часовой пояс
      - URL=m-zhitkov.ru                        # ★ ВАШ ГОЛОВНОЙ ДОМЕН
      - SUBDOMAINS=www                          # Поддомены через запятую (можно www,portainer)
      - VALIDATION=http                         # Способ проверки домена (через HTTP)
      - EMAIL=m-zhitkov@inbox.ru                # ★ ВАША ПОЧТА (для уведомлений Let's Encrypts
    volumes:
      - ./swag-config:/config                   # Папка для всех настроек SWAG на вашем сервере
      - ./nginx-conf:/config/nginx/site-confs:rw
    ports:
      - 80:80                                   # Порты 80 и 443 должны быть открыты
      - 443:443
    restart: unless-stopped
    networks:
      - app_network
    depends_on:
      django_app:
        condition: service_healthy
      vue_app:
        condition: service_started
networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
