server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: container_logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["com.docker.compose.project=finance"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'project'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'job'
      # Добавляем кастомные лейблы для приложений
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        regex: 'django_app'
        action: replace
        target_label: 'app'
        replacement: 'django'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        regex: 'fastapi'
        action: replace
        target_label: 'app'
        replacement: 'fastapi'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        regex: 'vue_app'
        action: replace
        target_label: 'app'
        replacement: 'vue'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        regex: 'nginx'
        action: replace
        target_label: 'app'
        replacement: 'nginx'