# Generated by Django 5.1.5 on 2025-01-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "ordering": ["name"],
                "verbose_name": "счет",
                "verbose_name_plural": "счета",
            },
        ),
    ]
