# Generated by Django 5.1.5 on 2025-01-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_transfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Показать/Скрыть"),
        ),
    ]
