# Generated by Django 5.1.5 on 2025-02-20 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_account_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transfer",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "перевод",
                "verbose_name_plural": "переводы",
            },
        ),
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrower_description", models.CharField(max_length=100)),
                (
                    "transfer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debt",
                        to="accounts.transfer",
                    ),
                ),
            ],
            options={
                "verbose_name": "долг",
                "verbose_name_plural": "долги",
            },
        ),
    ]
