# Generated by Django 5.1.5 on 2025-02-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_transfer_options_debt"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_system_account",
            field=models.BooleanField(default=False),
        ),
    ]
