# Generated by Django 5.1.5 on 2025-03-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_account_is_system_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transfer",
            name="destination_account",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="source_account",
        ),
        migrations.DeleteModel(
            name="Debt",
        ),
        migrations.DeleteModel(
            name="Transfer",
        ),
    ]
