# Generated by Django 5.1.5 on 2026-08-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_user",
            "0002_alter_customuser_managers_remove_customuser_username_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="yandex_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Yandex ID",
            ),
        ),
    ]
