# Generated by Django 5.1.5 on 2025-09-05 08:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0007_remove_transfer_destination_account_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "категория транзакции",
                "verbose_name_plural": "категории транзакций",
                "ordering": ("name",),
                "unique_together": {("name", "user")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal(
                                    "0.01000000000000000020816681711721685132943093776702880859375"
                                )
                            )
                        ],
                        verbose_name="Сумма транзакции",
                    ),
                ),
                (
                    "type_transaction",
                    models.CharField(
                        default="", max_length=20, verbose_name="Тип операции"
                    ),
                ),
                ("create_at", models.DateTimeField(verbose_name="Дата операции")),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=200,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.account",
                        verbose_name="Счет",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="transactions.category",
                        verbose_name="Тип расхода",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "транзакция",
                "verbose_name_plural": "транзакции",
                "db_table": "transactions",
                "ordering": ["-create_at", "-amount", "category__name"],
            },
        ),
    ]
