# Generated by Django 5.1.5 on 2025-09-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="type_transaction",
        ),
        migrations.AddField(
            model_name="category",
            name="type_transaction",
            field=models.CharField(
                default="", max_length=20, verbose_name="Тип операции"
            ),
        ),
    ]
