# Generated by Django 5.1.5 on 2025-09-05 14:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_remove_transaction_type_transaction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "user", "type_transaction")},
        ),
    ]
