# Generated by Django 5.1.5 on 2025-09-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_alter_category_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="type_transaction",
            field=models.CharField(max_length=20, verbose_name="Тип операции"),
        ),
    ]
