# Generated by Django 5.1.5 on 2026-03-07 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_alter_category_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("level", "name"),
                "verbose_name": "категория транзакции",
                "verbose_name_plural": "категории транзакций",
            },
        ),
        migrations.RemoveConstraint(
            model_name="category",
            name="unique_category_per_user_and_type",
        ),
        migrations.AddField(
            model_name="category",
            name="level",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Уровень вложенности"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="transactions.category",
                verbose_name="Родительская категория",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["user", "parent"], name="transaction_user_id_583d2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["level"], name="transaction_level_50b283_idx"),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name", "user", "type_transaction", "parent"),
                name="unique_subcategory_per_user_and_type",
            ),
        ),
    ]
