# Generated by Django 5.1.5 on 2026-03-08 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_alter_category_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="category",
            name="transaction_level_50b283_idx",
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["user", "level"], name="transaction_user_id_322263_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["user", "parent", "level"],
                name="transaction_user_id_5837e5_idx",
            ),
        ),
    ]
