# Generated by Django 5.1.5 on 2025-01-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="create_at",
            field=models.DateTimeField(verbose_name="Дата операции"),
        ),
    ]
