# Generated by Django 5.1.5 on 2025-03-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_expense_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="comment",
            field=models.TextField(
                blank=True,
                default="",
                max_length=200,
                null=True,
                verbose_name="Комментарий",
            ),
        ),
    ]
