# Generated by Django 5.1.5 on 2025-03-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0006_alter_expense_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={
                "ordering": ["-create_at", "-amount", "category__name"],
                "verbose_name": "расход",
                "verbose_name_plural": "расходы",
            },
        ),
    ]
